pipeline {
    agent {
        kubernetes {
            yaml '''
            apiVersion: v1
            kind: Pod
            metadata:
              name: jenkins-agent
            spec:
              containers:
              - name: gradle
                image: gradle:7.6.2-jdk17
                command:
                  - cat
                tty: true
              - name: docker
                image: docker:latest
                command:
                - cat
                tty: true
                volumeMounts:
                - mountPath: "/var/run/docker.sock"
                  name: docker-socket
              - name: kubectl
                image: gcr.io/cloud-builders/kubectl
                command:
                - cat
                tty: true
              volumes:
              - name: docker-socket
                hostPath:
                  path: "/var/run/docker.sock"
            '''
        }
    }

    environment {
        DOCKER_CREDENTIALS_ID = 'dockerhub_access'
        DOCKER_IMAGE_NAME = 'eunhee78/notification-service'
        DOCKERHUB_URL = 'https://index.docker.io/v1/'
        GITHUB_URL = 'git@github.com:beyond-sw-camp/be08-4th-DQ-OMOS.git'
        GITHUB_CREDENTIALS_ID = 'omos_access_ssh'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: "${GITHUB_CREDENTIALS_ID}", url: "${GITHUB_URL}"
            }
        }

        stage('Gradle Build') {
            steps {
                dir('Backend/notification-service') {
                    container('gradle') {
                        sh 'chmod +x ./gradlew'
                        sh './gradlew clean bootJar'
                    }
                }
            }
        }

        stage('Docker Image Build & Push') {
            steps {
                dir('Backend/notification-service') {
                    container('docker') {
                        script {
                            def dockerImageTag = "${env.BUILD_NUMBER}"
                            sh 'docker logout'
                            withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIALS_ID}", usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                                sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                            }
                            sh "docker build --no-cache -t ${DOCKER_IMAGE_NAME}:${dockerImageTag} ."
                            sh "docker push ${DOCKER_IMAGE_NAME}:${dockerImageTag}"
                            sh 'docker logout'
                        }
                    }
                }
            }
        }

        stage('Kubernetes Deployment') {
            steps {
                container('kubectl') {
                    script {
                        def dockerImageTag = "${env.BUILD_NUMBER}"
                        echo "DockerImageTag : ${dockerImageTag}"
                        sh 'kubectl set image deploy notification-deploy notification=$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG -n default'
                    }
                }
            }
        }
    }

    post {
        success {
            withCredentials([string(credentialsId: 'discord-webhook', variable: 'DISCORD')]) {
                discordSend description: """
                제목 : ${currentBuild.displayName}
                결과 : ${currentBuild.result}
                실행 시간 : ${currentBuild.duration / 1000}
                """,
                result: currentBuild.currentResult,
                title: "${env.JOB_NAME} : ${currentBuild.displayName} 성공",
                webhookURL: "${DISCORD}"
            }
        }
        failure {
            withCredentials([string(credentialsId: 'discord-webhook', variable: 'DISCORD')]) {
                discordSend description: """
                제목 : ${currentBuild.displayName}
                결과 : ${currentBuild.result}
                실행 시간 : ${currentBuild.duration / 1000}
                """,
                result: currentBuild.currentResult,
                title: "${env.JOB_NAME} : ${currentBuild.displayName} 실패",
                webhookURL: "${DISCORD}"
            }
        }
    }
}
