pipeline {
    agent {
        kubernetes {
            yaml '''
            apiVersion: v1
            kind: Pod
            metadata:
              name: jenkins-agent
            spec:
              containers:
              - name: gradle
                image: gradle:7.2-jdk17
                command:
                - cat
                tty: true
                volumeMounts:
                - mountPath: "/home/jenkins/agent"
                  name: workspace-volume
                  readOnly: false
              - name: docker
                image: docker:latest
                command:
                - cat
                tty: true
                volumeMounts:
                - mountPath: "/var/run/docker.sock"
                  name: docker-socket
                - mountPath: "/home/jenkins/agent"
                  name: workspace-volume
                  readOnly: false
              - name: kubectl
                image: bitnami/kubectl:latest
                command:
                - cat
                tty: true
                volumeMounts:
                - mountPath: "/home/jenkins/agent"
                  name: workspace-volume
                  readOnly: false
              - name: docker-compose
                image: docker/compose:latest
                command:
                - cat
                tty: true
                volumeMounts:
                - mountPath: "/var/run/docker.sock"
                  name: docker-socket
                - mountPath: "/home/jenkins/agent"
                  name: workspace-volume
                  readOnly: false
              volumes:
              - name: docker-socket
                hostPath:
                  path: "/var/run/docker.sock"
              - name: workspace-volume
                emptyDir: {}
            '''
        }
    }

    environment {
        DOCKER_CREDENTIALS_ID = 'dockerhub_access'
        DOCKER_IMAGE_NAME = 'jjjwww8802/student-service'
        DOCKERHUB_URL = 'https://index.docker.io/v1/'
        GITHUB_URL = 'git@github.com:beyond-sw-camp/be08-4th-DQ-OMOS.git'
        GITHUB_CREDENTIALS_ID = 'omos_student_access_ssh'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: "${GITHUB_CREDENTIALS_ID}", url: "${GITHUB_URL}"
            }
        }

        stage('Gradle Build') {
            steps {
                dir('Backend/student-service') {
                    container('gradle') {
                        script {
                            sh '''
                                chmod +x ./gradlew
                                ./gradlew clean build
                            '''
                        }
                    }
                }
            }
        }

        stage('Docker Image Build & Push') {
            steps {
                dir('Backend/student-service') {
                    container('docker') {
                        script {
                            def dockerImageTag = "${env.BUILD_NUMBER}"

                            echo "DockerImageTag : ${dockerImageTag}"

                            sh 'docker logout'
                            withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIALS_ID}", usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                                sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                            }

                            sh "docker build --no-cache -t ${DOCKER_IMAGE_NAME}:${dockerImageTag} ."
                            sh "docker push ${DOCKER_IMAGE_NAME}:${dockerImageTag}"

                            sh 'docker logout'
                        }
                    }
                }
            }
        }

        stage('Docker Compose Up') {
            steps {
                dir('Backend/student-service') {
                    container('docker-compose') {
                        script {
                            echo "Starting services with Docker Compose"
                            sh 'docker-compose up -d'
                        }
                    }
                }
            }
        }

        stage('Kubernetes Deploy') {
            steps {
                container('kubectl') {
                    script {
                        def dockerImageTag = "${env.BUILD_NUMBER}"

                        echo "Deploying DockerImageTag : ${dockerImageTag}"

                        sh "kubectl set image deploy student-deploy student=${DOCKER_IMAGE_NAME}:${dockerImageTag} -n default --record"
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Build and Deployment Successful"
        }
        failure {
            echo "Build or Deployment Failed"
        }
        always {
            deleteDir()
        }
    }
}
