pipeline {
    agent {
        kubernetes {
            yaml '''
            apiVersion: v1
            kind: Pod
            metadata:
              name: jenkins-agent
            spec:
              containers:
              - name: gradle
                image: gradle:7.2-jdk17
                command:
                - cat
                tty: true
              - name: docker
                image: docker:latest
                command:
                - cat
                tty: true
                volumeMounts:
                - mountPath: "/var/run/docker.sock"
                  name: docker-socket
              - name: kubectl
                image: bitnami/kubectl:latest
                command:
                - cat
                tty: true
              volumes:
              - name: docker-socket
                hostPath:
                  path: "/var/run/docker.sock"
            '''
        }
    }

    environment {
        DOCKER_CREDENTIALS_ID = 'dockerhub_access'  // dockerhub 자격증명 ID
        DOCKER_IMAGE_NAME = 'jjjwww8802/student-service'
        DOCKERHUB_URL = 'https://index.docker.io/v1/'
        GITHUB_URL = 'git@github.com:beyond-sw-camp/be08-4th-DQ-OMOS.git'
        GITHUB_CREDENTIALS_ID = 'omos_student_access_ssh'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: "${GITHUB_CREDENTIALS_ID}", url: "${GITHUB_URL}"
            }
        }

        stage('Gradle Build') {
            steps {
                dir('Backend/student-service') {
                    container('gradle') {
                        script {
                            // .env 파일을 읽어 환경 변수로 설정
                            sh 'set -o allexport; source .env; set +o allexport'
                            sh 'chmod +x ./gradlew'  // gradlew 실행 권한 부여
                            sh './gradlew clean build'  // 빌드 실행
                        }
                    }
                }
            }
        }

        stage('Docker Image Build & Push') {
            steps {
                dir('Backend/student-service') {
                    container('docker') {
                        script {
                            def dockerImageTag = "${env.BUILD_NUMBER}"

                            echo "DockerImageTag : ${dockerImageTag}"

                            sh 'docker logout'
                            withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIALS_ID}", usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                                sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                            }

                            // Docker 이미지 빌드 및 푸시
                            sh "docker build --no-cache -t ${DOCKER_IMAGE_NAME}:${dockerImageTag} ."
                            sh "docker push ${DOCKER_IMAGE_NAME}:${dockerImageTag}"

                            sh 'docker logout'
                        }
                    }
                }
            }
        }

        stage('Kubernetes Deploy') {
            steps {
                container('kubectl') {
                    script {
                        def dockerImageTag = "${env.BUILD_NUMBER}"

                        echo "Deploying DockerImageTag : ${dockerImageTag}"

                        sh "kubectl set image deploy student-deploy student=${DOCKER_IMAGE_NAME}:${dockerImageTag} -n default --record"
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Build and Deployment Successful"
        }
        failure {
            echo "Build or Deployment Failed"
        }
        always {
            cleanWs()  // 작업 공간 정리
        }
    }
}
