pipeline {
    agent {
        kubernetes {
            yaml '''
            apiVersion: v1
            kind: Pod
            metadata:
              name: jenkins-agent
            spec:
              containers:
              - name: gradle
                image: gradle:7.6.2-jdk17
                command:
                - cat
                tty: true
              - name: docker
                image: docker:27.2.0-alpine3.20
                command:
                - cat
                tty: true
                volumeMounts:
                - mountPath: "/var/run/docker.sock"
                  name: docker-socket
              - name: kubectl
                image: gcr.io/cloud-builders/kubectl
                command:
                - cat
                tty: true
              volumes:
              - name: docker-socket
                hostPath:
                  path: "/var/run/docker.sock"
            '''
        }
    }

    environment {
        DOCKER_IMAGE_NAME = 'jjjwww8802/auth-service'
    }

    stages {
        stage('Checkout') {
            steps {
                // Github에서 소스 코드를 체크아웃하는 단계
                git branch: 'main', 
                    credentialsId: 'omos_access_ssh', 
                    url: 'git@github.com:beyond-sw-camp/be08-4th-DQ-OMOS.git'
                sh 'pwd'
                sh 'ls -al'
            }
        }
        stage('Gradle Build') {
            steps {
                dir('Backend/auth-service') {  // Gradle 빌드가 필요한 정확한 디렉토리
                    container('gradle') {
                        sh 'pwd'
                        sh 'ls -al'
                        sh 'gradle clean build'
                        sh 'ls -al'
                        sh 'ls -al ./build/libs'
                    }
                }
            }
        }

        stage('Docker Image Build & Push') {
            steps {
                container('docker') {
                    script {
                        def dockerImageTag = "${env.BUILD_NUMBER}"

                        echo "DockerImageTag : ${dockerImageTag}"

                        sh 'docker logout'
                        withCredentials([usernamePassword(credentialsId: 'dockerhub_access', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                            sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                        }
                        withEnv(["DOCKER_IMAGE_TAG=${dockerImageTag}"]) {
                            sh 'docker build --no-cache -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG ./'
                            sh 'docker image inspect $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG'
                            sh 'docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG'
                        }
                        sh 'docker logout'
                    }
                }
            }
        }

        stage('Deployment') {
            steps {
                container('kubectl') {
                    script {
                        def dockerImageTag = "${env.BUILD_NUMBER}"

                        echo "DockerImageTag : ${dockerImageTag}"

                        withEnv(["DOCKER_IMAGE_TAG=${dockerImageTag}"]) {
                            sh 'kubectl set image deploy auth-deploy auth=$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG -n default'
                        }
                    }
                }
            }
        }
    }
}
